/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
        './resources/**/*.blade.php',
        './vendor/filament/**/*.blade.php',
        './Modules/**/*.blade.php',
        './Modules/**/*.php',
    ],
    safelist: [
        // Report Builder Grid System - safelist specific classes for reliable discovery
        'grid',
        'grid-cols-12',
        'col-span-1',
        'col-span-2',
        'col-span-3',
        'col-span-4',
        'col-span-6',
        'col-span-8',
        'col-span-9',
        'col-span-12',
        'gap-4',
        'gap-6',
        // Report Builder Band Colors (Filament semantic colors)
        'bg-warning-500',
        'bg-warning-600',
        'bg-danger-500',
        'bg-danger-600',
        'bg-primary-500',
        'bg-primary-600',
        'bg-success-500',
        'bg-success-600',
        'bg-info-500',
        'bg-info-600',
        'border-warning-700',
        'border-warning-800',
        'border-danger-700',
        'border-danger-800',
        'border-primary-700',
        'border-primary-800',
        'border-success-700',
        'border-success-800',
        'border-info-700',
        'border-info-800',
        // Common utility classes
        'rounded-xl',
        'rounded-2xl',
        'shadow-lg',
        'shadow-xl',
        'p-3',
        'p-4',
        'p-10',
        'sticky',
        'top-4',
    ],
    theme: {
        extend: {},
    },
    plugins: [],
};
