<?php

return [
    'ar' => 'Arabic',
    'az' => 'Azerbaijani',
    'ca' => 'Catalan',
    'cs' => 'Czech',
    'da' => 'Danish',
    'de' => 'German',
    'el' => 'Greek',
    'en' => 'English',
    'es' => 'Spanish',
    'et' => 'Estonian',
    'fa' => 'Persian',
    'fi' => 'Finnish',
    'fr' => 'French',
    'hr' => 'Croatian',
    'id' => 'Indonesian',
    'it' => 'Italian',
    'ja' => 'Japanese',
    'ko' => 'Korean',
    'lt' => 'Lithuanian',
    'lv' => 'Latvian',
    'nl' => 'Dutch',
    'no' => 'Norwegian',
    'pl' => 'Polish',
    'pt' => 'Portuguese',
    'ro' => 'Romanian',
    'sl' => 'Slovenian',
    'sq' => 'Albanian',
    'sv' => 'Swedish',
    'th' => 'Thai',
    'tr' => 'Turkish',
    'vi' => 'Vietnamese',
    'zh' => 'Chinese',
];
