<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Report Block Available Fields
    |--------------------------------------------------------------------------
    |
    | This configuration defines all available fields that can be used in
    | report blocks. Fields are now stored in a flat array structure with
    | a "source" property for grouping. This eliminates nested foreach loops
    | and provides the exact structure Alpine.js expects.
    |
    */

    ['id' => 'company_name', 'label' => 'ip.report_field_company_name', 'source' => 'company'],
    ['id' => 'company_address_1', 'label' => 'ip.report_field_company_address_1', 'source' => 'company'],
    ['id' => 'company_address_2', 'label' => 'ip.report_field_company_address_2', 'source' => 'company'],
    ['id' => 'company_city', 'label' => 'ip.report_field_company_city', 'source' => 'company'],
    ['id' => 'company_state', 'label' => 'ip.report_field_company_state', 'source' => 'company'],
    ['id' => 'company_zip', 'label' => 'ip.report_field_company_zip', 'source' => 'company'],
    ['id' => 'company_country', 'label' => 'ip.report_field_company_country', 'source' => 'company'],
    ['id' => 'company_phone', 'label' => 'ip.report_field_company_phone', 'source' => 'company'],
    ['id' => 'company_email', 'label' => 'ip.report_field_company_email', 'source' => 'company'],
    ['id' => 'company_vat_id', 'label' => 'ip.report_field_company_vat_id', 'source' => 'company'],
    ['id' => 'company_id_number', 'label' => 'ip.report_field_company_id_number', 'source' => 'company'],
    ['id' => 'company_coc_number', 'label' => 'ip.report_field_company_coc_number', 'source' => 'company'],
    ['id' => 'customer_name', 'label' => 'ip.report_field_customer_name', 'source' => 'customer'],
    ['id' => 'customer_address_1', 'label' => 'ip.report_field_customer_address_1', 'source' => 'customer'],
    ['id' => 'customer_address_2', 'label' => 'ip.report_field_customer_address_2', 'source' => 'customer'],
    ['id' => 'customer_city', 'label' => 'ip.report_field_customer_city', 'source' => 'customer'],
    ['id' => 'customer_state', 'label' => 'ip.report_field_customer_state', 'source' => 'customer'],
    ['id' => 'customer_zip', 'label' => 'ip.report_field_customer_zip', 'source' => 'customer'],
    ['id' => 'customer_country', 'label' => 'ip.report_field_customer_country', 'source' => 'customer'],
    ['id' => 'customer_phone', 'label' => 'ip.report_field_customer_phone', 'source' => 'customer'],
    ['id' => 'customer_email', 'label' => 'ip.report_field_customer_email', 'source' => 'customer'],
    ['id' => 'customer_vat_id', 'label' => 'ip.report_field_customer_vat_id', 'source' => 'customer'],
    ['id' => 'invoice_number', 'label' => 'ip.report_field_invoice_number', 'source' => 'invoice'],
    ['id' => 'invoice_date', 'label' => 'ip.report_field_invoice_date', 'source' => 'invoice', 'format' => 'date'],
    ['id' => 'invoice_date_created', 'label' => 'ip.report_field_invoice_date_created', 'source' => 'invoice', 'format' => 'date'],
    ['id' => 'invoice_date_due', 'label' => 'ip.report_field_invoice_date_due', 'source' => 'invoice', 'format' => 'date'],
    ['id' => 'invoice_guest_url', 'label' => 'ip.report_field_invoice_guest_url', 'source' => 'invoice', 'format' => 'url'],
    ['id' => 'invoice_item_subtotal', 'label' => 'ip.report_field_invoice_item_subtotal', 'source' => 'invoice', 'format' => 'currency'],
    ['id' => 'invoice_item_tax_total', 'label' => 'ip.report_field_invoice_item_tax_total', 'source' => 'invoice', 'format' => 'currency'],
    ['id' => 'invoice_total', 'label' => 'ip.report_field_invoice_total', 'source' => 'invoice', 'format' => 'currency'],
    ['id' => 'invoice_paid', 'label' => 'ip.report_field_invoice_paid', 'source' => 'invoice', 'format' => 'currency'],
    ['id' => 'invoice_balance', 'label' => 'ip.report_field_invoice_balance', 'source' => 'invoice', 'format' => 'currency'],
    ['id' => 'invoice_status', 'label' => 'ip.report_field_invoice_status', 'source' => 'invoice'],
    ['id' => 'invoice_notes', 'label' => 'ip.report_field_invoice_notes', 'source' => 'invoice'],
    ['id' => 'invoice_terms', 'label' => 'ip.report_field_invoice_terms', 'source' => 'invoice'],
    ['id' => 'item_description', 'label' => 'ip.report_field_item_description', 'source' => 'invoice_item'],
    ['id' => 'item_name', 'label' => 'ip.report_field_item_name', 'source' => 'invoice_item'],
    ['id' => 'item_quantity', 'label' => 'ip.report_field_item_quantity', 'source' => 'invoice_item', 'format' => 'number'],
    ['id' => 'item_price', 'label' => 'ip.report_field_item_price', 'source' => 'invoice_item', 'format' => 'currency'],
    ['id' => 'item_subtotal', 'label' => 'ip.report_field_item_subtotal', 'source' => 'invoice_item', 'format' => 'currency'],
    ['id' => 'item_tax_name', 'label' => 'ip.report_field_item_tax_name', 'source' => 'invoice_item'],
    ['id' => 'item_tax_rate', 'label' => 'ip.report_field_item_tax_rate', 'source' => 'invoice_item', 'format' => 'percentage'],
    ['id' => 'item_tax_amount', 'label' => 'ip.report_field_item_tax_amount', 'source' => 'invoice_item', 'format' => 'currency'],
    ['id' => 'item_total', 'label' => 'ip.report_field_item_total', 'source' => 'invoice_item', 'format' => 'currency'],
    ['id' => 'item_discount', 'label' => 'ip.report_field_item_discount', 'source' => 'invoice_item', 'format' => 'currency'],
    ['id' => 'quote_number', 'label' => 'ip.report_field_quote_number', 'source' => 'quote'],
    ['id' => 'quote_date', 'label' => 'ip.report_field_quote_date', 'source' => 'quote', 'format' => 'date'],
    ['id' => 'quote_date_created', 'label' => 'ip.report_field_quote_date_created', 'source' => 'quote', 'format' => 'date'],
    ['id' => 'quote_date_expires', 'label' => 'ip.report_field_quote_date_expires', 'source' => 'quote', 'format' => 'date'],
    ['id' => 'quote_guest_url', 'label' => 'ip.report_field_quote_guest_url', 'source' => 'quote', 'format' => 'url'],
    ['id' => 'quote_subtotal', 'label' => 'ip.report_field_quote_subtotal', 'source' => 'quote', 'format' => 'currency'],
    ['id' => 'quote_tax_total', 'label' => 'ip.report_field_quote_tax_total', 'source' => 'quote', 'format' => 'currency'],
    ['id' => 'quote_discount', 'label' => 'ip.report_field_quote_discount', 'source' => 'quote', 'format' => 'currency'],
    ['id' => 'quote_total', 'label' => 'ip.report_field_quote_total', 'source' => 'quote', 'format' => 'currency'],
    ['id' => 'quote_status', 'label' => 'ip.report_field_quote_status', 'source' => 'quote'],
    ['id' => 'quote_notes', 'label' => 'ip.report_field_quote_notes', 'source' => 'quote'],
    ['id' => 'quote_item_description', 'label' => 'ip.report_field_quote_item_description', 'source' => 'quote_item'],
    ['id' => 'quote_item_name', 'label' => 'ip.report_field_quote_item_name', 'source' => 'quote_item'],
    ['id' => 'quote_item_quantity', 'label' => 'ip.report_field_quote_item_quantity', 'source' => 'quote_item', 'format' => 'number'],
    ['id' => 'quote_item_price', 'label' => 'ip.report_field_quote_item_price', 'source' => 'quote_item', 'format' => 'currency'],
    ['id' => 'quote_item_subtotal', 'label' => 'ip.report_field_quote_item_subtotal', 'source' => 'quote_item', 'format' => 'currency'],
    ['id' => 'quote_item_tax_name', 'label' => 'ip.report_field_quote_item_tax_name', 'source' => 'quote_item'],
    ['id' => 'quote_item_tax_rate', 'label' => 'ip.report_field_quote_item_tax_rate', 'source' => 'quote_item', 'format' => 'percentage'],
    ['id' => 'quote_item_total', 'label' => 'ip.report_field_quote_item_total', 'source' => 'quote_item', 'format' => 'currency'],
    ['id' => 'quote_item_discount', 'label' => 'ip.report_field_quote_item_discount', 'source' => 'quote_item', 'format' => 'currency'],
    ['id' => 'payment_date', 'label' => 'ip.report_field_payment_date', 'source' => 'payment', 'format' => 'date'],
    ['id' => 'payment_amount', 'label' => 'ip.report_field_payment_amount', 'source' => 'payment', 'format' => 'currency'],
    ['id' => 'payment_method', 'label' => 'ip.report_field_payment_method', 'source' => 'payment'],
    ['id' => 'payment_note', 'label' => 'ip.report_field_payment_note', 'source' => 'payment'],
    ['id' => 'payment_reference', 'label' => 'ip.report_field_payment_reference', 'source' => 'payment'],
    ['id' => 'project_name', 'label' => 'ip.report_field_project_name', 'source' => 'project'],
    ['id' => 'project_description', 'label' => 'ip.report_field_project_description', 'source' => 'project'],
    ['id' => 'project_start_date', 'label' => 'ip.report_field_project_start_date', 'source' => 'project', 'format' => 'date'],
    ['id' => 'project_end_date', 'label' => 'ip.report_field_project_end_date', 'source' => 'project', 'format' => 'date'],
    ['id' => 'project_status', 'label' => 'ip.report_field_project_status', 'source' => 'project'],
    ['id' => 'task_name', 'label' => 'ip.report_field_task_name', 'source' => 'task'],
    ['id' => 'task_description', 'label' => 'ip.report_field_task_description', 'source' => 'task'],
    ['id' => 'task_start_date', 'label' => 'ip.report_field_task_start_date', 'source' => 'task', 'format' => 'date'],
    ['id' => 'task_finish_date', 'label' => 'ip.report_field_task_finish_date', 'source' => 'task', 'format' => 'date'],
    ['id' => 'task_hours', 'label' => 'ip.report_field_task_hours', 'source' => 'task', 'format' => 'number'],
    ['id' => 'task_rate', 'label' => 'ip.report_field_task_rate', 'source' => 'task', 'format' => 'currency'],
    ['id' => 'expense_date', 'label' => 'ip.report_field_expense_date', 'source' => 'expense', 'format' => 'date'],
    ['id' => 'expense_category', 'label' => 'ip.report_field_expense_category', 'source' => 'expense'],
    ['id' => 'expense_amount', 'label' => 'ip.report_field_expense_amount', 'source' => 'expense', 'format' => 'currency'],
    ['id' => 'expense_description', 'label' => 'ip.report_field_expense_description', 'source' => 'expense'],
    ['id' => 'expense_vendor', 'label' => 'ip.report_field_expense_vendor', 'source' => 'expense'],
    ['id' => 'relation_name', 'label' => 'ip.report_field_relation_name', 'source' => 'relation'],
    ['id' => 'relation_address_1', 'label' => 'ip.report_field_relation_address_1', 'source' => 'relation'],
    ['id' => 'relation_address_2', 'label' => 'ip.report_field_relation_address_2', 'source' => 'relation'],
    ['id' => 'relation_city', 'label' => 'ip.report_field_relation_city', 'source' => 'relation'],
    ['id' => 'relation_state', 'label' => 'ip.report_field_relation_state', 'source' => 'relation'],
    ['id' => 'relation_zip', 'label' => 'ip.report_field_relation_zip', 'source' => 'relation'],
    ['id' => 'relation_country', 'label' => 'ip.report_field_relation_country', 'source' => 'relation'],
    ['id' => 'relation_phone', 'label' => 'ip.report_field_relation_phone', 'source' => 'relation'],
    ['id' => 'relation_email', 'label' => 'ip.report_field_relation_email', 'source' => 'relation'],
    ['id' => 'sumex_casedate', 'label' => 'ip.report_field_sumex_casedate', 'source' => 'sumex', 'format' => 'date'],
    ['id' => 'sumex_casenumber', 'label' => 'ip.report_field_sumex_casenumber', 'source' => 'sumex'],
    ['id' => 'current_date', 'label' => 'ip.report_field_current_date', 'source' => 'common', 'format' => 'date'],
    ['id' => 'footer_notes', 'label' => 'ip.report_field_footer_notes', 'source' => 'common'],
    ['id' => 'page_number', 'label' => 'ip.report_field_page_number', 'source' => 'common'],
    ['id' => 'total_pages', 'label' => 'ip.report_field_total_pages', 'source' => 'common'],
];
