<?php

declare(strict_types=1);

namespace Fable5\Execution;

use Fable5\Logging\Logger;
use Fable5\Git\GitRepository;
use Fable5\Git\PullRequestManager;

final class ExecutionRunner
{
    public function __construct(
        private Logger $logger,
        private GitRepository $git,
        private PullRequestManager $prManager
    ) {}

    public function run(ExecutionGraph $graph, array $schedule): void
    {
        foreach ($schedule as $layerIndex => $layer) {
            $this->logger->info("Executing layer {$layerIndex}", ['nodes' => $layer]);

            foreach ($layer as $nodeId) {
                $node = $graph->getNode($nodeId);
                $this->executeNode($node);
            }
        }
    }

    private function executeNode(ExecutionNode $node): void
    {
        $this->logger->info("Executing node {$node->getId()}", ['type' => $node->getType()]);

        $payload = $node->getPayload();
        $branchName = $payload['branch'] ?? "fable5/issue-{$node->getId()}";

        switch ($node->getType()) {
            case 'issue':
                $this->processIssueNode($node, $branchName);
                break;

            default:
                $this->logger->warning("Unknown node type: {$node->getType()}");
        }
    }

    private function processIssueNode(ExecutionNode $node, string $branchName): void
    {
        // 1. Check if PR already exists for this branch
        $existingPr = $this->prManager->findExistingPRForBranch($branchName);

        if ($existingPr) {
            $this->logger->info("PR already exists for branch {$branchName}, updating...", ['pr' => $existingPr['number']]);
            // Logic to update PR if needed
            return;
        }

        // 2. Prepare branch
        $this->logger->info("Creating branch {$branchName}");
        try {
            $this->git->exec(['checkout', '-b', $branchName]);
        } catch (\Exception $e) {
            $this->logger->info("Branch {$branchName} might already exist locally, checking it out");
            $this->git->checkout($branchName);
        }

        // 3. Perform work (In a real scenario, this would apply the fix)
        $this->logger->info("Applying changes for node {$node->getId()}");
        // placeholder for actual code modification logic

        // 4. Commit and Push
        $this->logger->info("Committing and pushing changes");
        // $this->git->exec(['add', '.']);
        // $this->git->exec(['commit', '-m', "Fix issue #{$node->getId()}"]);
        // $this->git->push('origin', $branchName);

        // 5. Create Pull Request
        $this->logger->info("Opening Pull Request");
        // $this->prManager->create(
        //     title: "Fix issue #{$node->getId()}: " . ($node->getPayload()['title'] ?? ''),
        //     body: "Automatically generated by Fable5.\n\nCloses #{$node->getId()}",
        //     head: $branchName
        // );
    }
}
